### PR TITLE
Preserve comments when replacing nodes

### LINKED ISSUE #705: comments get deleted
## Describe the bug

Some refactorings delete leading/trailing comments in the current block.
This breaks userscripts where they are necessary: https://wiki.greasespot.net/Metadata_Block.

## How to reproduce

```js
// some comment
const x = 1, y = 2;
```
Run the `Split multiple declarations` refactoring:
```js
const x = 1;
const y = 2;
```

## Expected behavior

Retain the comments:
```js
// some comment
const x = 1;
const y = 2;
```

## Additional information

- Version of the extension impacted: _v6.15.3_
- Also happens with `Split declaration and initialization`, `Convert ternary if/else` and probably others. All seem to be related to `path.replaceWith/replaceWithMultiple`

### PR DESCRIPTION
**Pull request by chrstnbrn**
Fixes #705

Some refactorings deleted comments (e.g. `Split multiple declarations`) because `path.replaceWith/replaceWithMultiple` does not inherit the `comments` property added by recast. I fixed this by creating and calling `replaceWithPreservingComments/replaceWithMultiplePreservingComments` instead.

### CODE REVIEW

File: src/ast/transformation.ts [hunk 1]
```diff
@@ -249,16 +249,43 @@ export function mergeCommentsInto<T extends t.Node>(
...
+  path: NodePath,
+  replacement: t.Node | NodePath<t.Node>
+) {
+  const replacementPath = path.replaceWith(replacement);
+  if (replacementPath[0]) {
+    preserveCommentsForRecast(replacementPath[0]);
+  }
+}
+
+export function replaceWithMultiplePreservingComments(
```
Comment (nicoespeon) [inline src/ast/transformation.ts:279]: 👍 Kudos for creating a simple, dedicated method for that.

File: src/refactorings/convert-for-each-to-for-of/convert-for-each-to-for-of.test.ts [hunk 2]
```diff
@@ -169,6 +169,42 @@ items.forEach((item) => {
...
+});`,
+        expected: `
+for (const item of items) {
+  if (item.type === 'foo') {
+    // leading comment
+    continue;
+    // trailing comment
+  }
+  console.log(item);
+}`
```
Comment (nicoespeon) [inline src/refactorings/convert-for-each-to-for-of/convert-for-each-to-for-of.test.ts:207]: 👍 Super-kudos for adding tests to prove it's working as expected and prevent regressions!

File: src/refactorings/convert-to-arrow-function/convert-to-arrow-function.ts [hunk 3]
```diff
@@ -73,11 +73,7 @@ class FunctionDeclarationConverter implements Converter {
       t.toArrowFunctionExpression(this.path)
     );
 
-    const variableDeclaration = t.variableDeclaration("const", [declarator]);
-    // @ts-expect-error Recast does use a `comments` attribute.
-    variableDeclaration.comments = node.comments;
-
-    return variableDeclaration;
```
Comment (nicoespeon) [inline src/refactorings/convert-to-arrow-function/convert-to-arrow-function.ts:80]: Nice cleanup!

**Review by nicoespeon — APPROVED** [review]

**Comment by nicoespeon** [comment]
Amazing work @chrstnbrn, thanks for the great PR 👏

**Comment by nicoespeon** [comment]
@all-contributors please add chrstnbrn for bugs
